version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-database:/docker-entrypoint-initdb.d   # copy initialization script to docker entrypoint directory
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres-data:
